apiVersion: v1
kind: Service
metadata:
  name: lb-svc-grafana
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: prometheus-1
    app.kubernetes.io/name: grafana
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000

